name: vodid_prototype2
description: Vodid prototype
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.2.0

  # Cihaz & konum
  device_info_plus: ^9.1.2
  location: ^5.0.3
  geocoding: ^2.1.1

  # Medya
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2

  # Yerelleştirme (Flutter SDK içinden)
  flutter_localizations:
    sdk: flutter
  # intl, flutter_localizations 0.20.2 istediği için bu sürümde olmalı
  intl: ^0.20.2

  # FlutterFire (aynı majör serilerde tut)
  firebase_core: ^3.15.2
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.1

  # Google Sign-In
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
