name: vodid_prototype2
description: Vodid prototype
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  device_info_plus: ^9.1.2
  location: ^5.0.3
  geocoding: ^2.1.1
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2
  share_plus: ^9.0.0

  # FlutterFire (Tüm paketler uyumlu sürümlere güncellendi)
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  cloud_functions: ^4.7.5

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Tarih formatı
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true