name: vodid_prototype2
description: Vodid prototype
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  cloud_functions: ^4.6.0
  google_sign_in: ^6.2.1
  
  video_player: ^2.8.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

# --- NİHAİ ÇÖZÜM: TÜM ÇATIŞMALARI EZEN BÖLÜM ---
dependency_overrides:
  firebase_core_platform_interface: 5.0.0
# --------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700