// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// // await Firebase.initializeApp(
/// // options: DefaultFirebaseOptions.currentPlatform,
/// // );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSiMf0Ji226u8Sc8OMNoau-qRen_RUsU',
    appId: '1:1025205651223:web:eedb16cfee6eac0a485952',
    messagingSenderId: '1025205651223',
    projectId: 'vodid2',
    authDomain: 'vodid2.firebaseapp.com',
    storageBucket: 'vodid2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDr1m3HedtDGGlqjJxoujiLj31wYFRdWw',
    appId: '1:1025205651223:android:4387cb8395510c03485952',
    messagingSenderId: '1025205651223',
    projectId: 'vodid2',
    storageBucket: 'vodid2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYyoyov001u4WEi1uuXMtOUNZd9v49aU',
    appId: '1:1025205651223:ios:44ef71b4ecea0ec3485952',
    messagingSenderId: '1025205651223',
    projectId: 'vodid2',
    storageBucket: 'vodid2.firebasestorage.app',
    iosBundleId: 'com.example.vodidPrototype2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYyoyov001u4WEi1uuXMtOUNZd9v49aU',
    appId: '1:1025205651223:ios:44ef71b4ecea0ec3485952',
    messagingSenderId: '1025205651223',
    projectId: 'vodid2',
    storageBucket: 'vodid2.firebasestorage.app',
    iosBundleId: 'com.example.vodidPrototype2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhSiMf0Ji226u8Sc8OMNoau-qRen_RUsU',
    appId: '1:1025205651223:web:2cd3aedef21ce1b5485952',
    messagingSenderId: '1025205651223',
    projectId: 'vodid2',
    authDomain: 'vodid2.firebaseapp.com',
    storageBucket: 'vodid2.firebasestorage.app',
  );
}
